PFS:
  raw_dir: "data/raw/trials"
  data_dir: "data/PFS"
  pred_dir: "tables/PFS_prediction"
  table_dir: "tables"
  fig_dir: "figures"
  metadata_sheet: "data/mCRPC_PFS_sheet.txt"
  metadata_sheet_seed: "data/mCRPC_PFS_sheet_with_seed.txt"

rPFS:
  raw_dir: "data/raw/trials"
  data_dir: "data/rPFS"
  pred_dir: "tables/rPFS_prediction"
  table_dir: "tables"
  fig_dir: "figures"
  metadata_sheet: "data/mCRPC_rPFS_sheet.txt"
  metadata_sheet_seed: "data/mCRPC_rPFS_sheet_with_seed.txt"

waterfall:
  raw_dir: "data/raw/trials"
  data_dir: "data/waterfall"
  pred_dir: "tables/waterfall_prediction"
  table_dir: "tables"
  fig_dir: "figures"
  metadata_sheet: "data/mCRPC_waterfall_sheet.txt"
  metadata_sheet_seed: "data/mCRPC_waterfall_sheet_with_seed.txt"

experimental_dir: "data/experimental"
table_dir: "tables"
temp_dir: "tables/temp"
fig_dir: "figures"
